filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/b202d819663ad0805ebb6360119d4c365cc1b5c03d12516793d1386983d27a89/b202d819663ad0805ebb6360119d4c365cc1b5c03d12516793d1386983d27a89.log'
  json.keys_under_root: true
  json.add_error_key: true
  json.message_key: log
  
processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"
- dissect:
    tokenizer: "%{type} %{time} %{uuid} %{channel} %{id} %{chaincode} %{method} %{specificinfo}"
    field: "message"       
    target_prefix: "dissect"

output.elasticsearch:
  hosts: ["localhost:9200"]
  username: "elastic"
  password: "changeme"
  indices:
    - index:

logging.json: true
logging.metrics.enabled: false