filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/cf6ab3907704809fdc7b27d8cbaf8851b967e2c2b0d69812b965114aa67ce753/cf6ab3907704809fdc7b27d8cbaf8851b967e2c2b0d69812b965114aa67ce753.log'
  json.keys_under_root: true
  json.add_error_key: true
  json.message_key: log
  
processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"
- dissect:
    tokenizer: "%{type} %{time} %{uuid} %{channel} %{id} %{chaincode} %{method} %{specificinfo}"
    field: "message"       
    target_prefix: "dissect"

output.elasticsearch:
  hosts: ["localhost:9200"]
  username: "elastic"
  password: "changeme"
  indices:
    - index:

logging.json: true
logging.metrics.enabled: false